dumb :
	gcc -Wall -shared -fpic -o malloc_dumb.so malloc_dumb.c

fixed :
	gcc -Wall -shared -fpic -o malloc_fixed.so malloc_fixed.c

fixed_threadsafe :
	gcc -Wall -shared -fpic -lpthread -o malloc_ftsafe.so malloc_fixed_threadsafe.c

fixed_mmap :
	gcc -Wall -shared -fpic -o malloc_fmmap.so malloc_fixed_mmap.c
